name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'Added'
    labels:
      - enhancement
      - feature
  - title: 'Changed'
    labels:
      - chore
      - ci
      - refactor
  - title: 'Fixed'
    labels:
      - bug
  - title: 'Documentation'
    labels:
      - documentation
      - docs
  - title: 'Dependencies'
    labels:
      - dependencies
  - title: 'Other Changes'

