repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: helm-docs
        entry: bash scripts/pre-commit-helm-docs.sh
        language: system
        pass_filenames: false
      - id: helm-schema
        name: helm-values-schema
        entry: bash scripts/pre-commit-helm-schema.sh
        language: system
        pass_filenames: false
