{{- if or .Values.podSecurity.enforce .Values.podSecurity.audit .Values.podSecurity.warn }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "n8n.fullname" . }}-podsecurity
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - >-
              kubectl label --overwrite namespace {{ .Release.Namespace }}
              {{- if .Values.podSecurity.enforce }} pod-security.kubernetes.io/enforce={{ .Values.podSecurity.enforce }}{{- end }}
              {{- if .Values.podSecurity.audit }} pod-security.kubernetes.io/audit={{ .Values.podSecurity.audit }}{{- end }}
              {{- if .Values.podSecurity.warn }} pod-security.kubernetes.io/warn={{ .Values.podSecurity.warn }}{{- end }}
{{- end }}

