{{- if .Values.generateDatabasePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-db-password
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
{{- if .Values.generateEncryptionKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-encryption-key
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  encryptionKey: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
