{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-metrics
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.metrics.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
{{- end }}
