name: Setup Helm Tools
runs:
  using: composite
  steps:
    - name: Setup Helm
      uses: azure/setup-helm@v4
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
    - name: Add Bitnami repo
      run: helm repo add bitnami https://charts.bitnami.com/bitnami
    - name: Build chart dependencies
      run: helm dependency build n8n
    - name: Install helm-docs
      run: |
        if [ ! -f /usr/local/bin/helm-docs ]; then
          curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz | tar -xz -C /usr/local/bin helm-docs
        fi
    - name: Install helm-unittest plugin
      run: |
        if [ ! -d "$HOME/.local/share/helm/plugins/helm-unittest" ]; then
          helm plugin install https://github.com/helm-unittest/helm-unittest
        fi
    - name: Install helm-schema-gen plugin
      run: |
        if [ ! -d "$HOME/.local/share/helm/plugins/helm-schema-gen" ]; then
          helm plugin install https://github.com/karuppiah7890/helm-schema-gen.git
        fi
