---
name: Setup Helm Tools
inputs:
  chart_dir:
    description: Path to the Helm chart
    required: false
    default: n8n
runs:
  using: composite
  steps:
    - name: Cache Helm plugins and helm-docs
      id: plugins-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.HOME }}/.local/share/helm/plugins
          /usr/local/bin/helm-docs
        key: helm-plugins-${{ env.HELM_VERSION }}
        restore-keys: |
          helm-plugins-
    - name: Cache chart dependencies
      id: charts-cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.chart_dir }}/charts
        key: >
          charts-${{ hashFiles(
            format('{0}/Chart.lock', inputs.chart_dir),
            format('{0}/Chart.yaml', inputs.chart_dir)
          ) }}  # yamllint disable-line rule:line-length
        restore-keys: |
          charts-
    - name: Build chart dependencies
      if: steps.charts-cache.outputs.cache-hit != 'true'
      run: helm dependency build ${{ inputs.chart_dir }}
      shell: bash
    - name: Ensure helm-schema-gen plugin
      run: |
        if ! helm plugin list | grep -qw schema-gen; then
          helm plugin install \
            https://github.com/karuppiah7890/helm-schema-gen.git
        fi
      shell: bash
