name: Check PostgreSQL Chart Version

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Helm version
        run: echo "HELM_VERSION=$(cat .github/helm-version.txt)" >> "$GITHUB_ENV"
      - name: Cache Helm plugins and helm-docs
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.HOME }}/.local/share/helm/plugins
            /usr/local/bin/helm-docs
          key: helm-plugins-${{ env.HELM_VERSION }}
      - name: Setup Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Add Helm repository
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
      - name: Get latest PostgreSQL version
        id: latest
        run: |
          latest=$(helm search repo bitnami/postgresql --versions | awk 'NR==2{print $2}')
          echo "latest=$latest" >> "$GITHUB_OUTPUT"
      - name: Get chart version
        id: current
        run: |
          current=$(grep -A2 'name: postgresql' n8n/Chart.yaml | grep version | awk '{print $2}')
          echo "current=$current" >> "$GITHUB_OUTPUT"
      - name: Install helm-docs
        if: steps.latest.outputs.latest != steps.current.outputs.current
        run: |
          if [ ! -f /usr/local/bin/helm-docs ]; then
            curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz \
              | tar -xz -C /usr/local/bin helm-docs
          fi
      - name: Update files
        if: steps.latest.outputs.latest != steps.current.outputs.current
        run: |
          sed -i -E "/name: postgresql/{n;s/version: .*/version: ${{ steps.latest.outputs.latest }}/;}" n8n/Chart.yaml
          helm-docs
      - name: Create Pull Request
        if: steps.latest.outputs.latest != steps.current.outputs.current
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update postgresql chart version to ${{ steps.latest.outputs.latest }}"
          title: "chore: update postgresql chart version to ${{ steps.latest.outputs.latest }}"
          body: "Automated update of PostgreSQL chart dependency to ${{ steps.latest.outputs.latest }}."
          branch: "update-postgresql-${{ steps.latest.outputs.latest }}"
          delete-branch: true
          labels: automated
      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
