name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Add Helm repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Build chart dependencies
        run: helm dependency build n8n
      - name: Install helm-docs
        run: |
          curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz \
            | tar -xz -C /usr/local/bin helm-docs
      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest
      - name: Install helm-schema-gen plugin
        run: helm plugin install https://github.com/karuppiah7890/helm-schema-gen.git
      - name: Verify chart documentation
        run: |
          helm-docs
          git diff --exit-code
      - name: Build chart dependencies
        run: helm dependency build n8n
      - name: Helm lint
        run: helm lint n8n
      - name: Helm lint with values
        run: helm lint n8n --values n8n/values.yaml
      - name: Helm unit tests
        run: helm unittest n8n
      - name: Helm template
        run: helm template n8n
      - name: Validate values schema
        run: |
          helm schema-gen n8n/values.yaml > generated-values.schema.json
          jq --indent 4 '.properties.ingress.properties.hosts.items.properties.paths.items.properties.pathType += {"enum": ["ImplementationSpecific", "Prefix", "Exact"]}' generated-values.schema.json > tmp.json
          mv tmp.json generated-values.schema.json
          diff -u n8n/values.schema.json generated-values.schema.json
      - name: Get chart version
        id: chart
        run: |
          version=$(grep '^appVersion:' n8n/Chart.yaml | awk '{print $2}' | tr -d '"')
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Scan chart for vulnerabilities
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: fs
          scan-ref: n8n
          exit-code: 1
          severity: HIGH
          args: --ignorefile .trivyignore
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://github.com/aquasecurity/trivy/releases/download/v0.63.0/trivy_0.63.0_Linux-64bit.deb > trivy.deb
          sudo dpkg -i trivy.deb
          rm trivy.deb
      - name: Scan container image for vulnerabilities
        run: |
          trivy image n8nio/n8n:${{ steps.chart.outputs.version }} \
            --severity HIGH,CRITICAL --exit-code 1 --ignorefile .trivyignore

  install:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        with:
          wait: 120s
      - name: Check cluster readiness
        run: kubectl get nodes && kubectl get pods --all-namespaces
      - name: Add Helm repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Build chart dependencies
        run: helm dependency build ./n8n
      - name: Install chart
        run: helm install my-n8n ./n8n --wait --timeout 300s
      - name: Debug Helm installation
        if: failure()
        run: |
          kubectl describe pods -n default || true
          kubectl logs -l "app.kubernetes.io/name=n8n,app.kubernetes.io/instance=my-n8n" -n default || true
      - name: Wait for pods
        run: kubectl wait --namespace default --for=condition=ready pod -l "app.kubernetes.io/name=n8n,app.kubernetes.io/instance=my-n8n" --timeout=300s
      - name: Get pods
        run: kubectl get pods -n default
      - name: Delete release
        run: helm uninstall my-n8n
