name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v3
      - name: Install helm-docs
        run: |
          curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz \
            | tar -xz -C /usr/local/bin helm-docs
      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest
      - name: Verify chart documentation
        run: |
          helm-docs
          git diff --exit-code
      - name: Helm lint
        run: helm lint n8n
      - name: Helm lint with values
        run: helm lint --values n8n/values.yaml
      - name: Helm unit tests
        run: helm unittest n8n
      - name: Helm template
        run: helm template n8n
      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@0.14.0
        with:
          scan-type: fs
          scan-ref: n8n
          exit-code: 1
          severity: HIGH

