name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      n8n: ${{ steps.filter.outputs.n8n }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            n8n:
              - 'n8n/**'
              - '!n8n/README.md'
              - '!n8n/docs/**'

  pre-commit:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.n8n == 'true'
    # Use a tagged image to avoid pulling the floating `latest`
    container:
      image: ghcr.io/${{ github.repository_owner }}/helm-tools:v1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Helm version
        run: echo "HELM_VERSION=$(cat .github/helm-version.txt)" >> "$GITHUB_ENV"
      - name: Setup Helm tools
        uses: ./.github/actions/setup-helm-tools
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files $(if [ -n "${{ github.event.pull_request.base.sha }}" ]; then git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }}; else git ls-files; fi)
          cache: true
