name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Cache Helm plugins and helm-docs
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.HOME }}/.local/share/helm/plugins
            /usr/local/bin/helm-docs
          key: ${{ runner.os }}-helm-plugins-v1
      - name: Setup Helm tools
        uses: ./.github/actions/setup-helm-tools
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
