name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/upload-artifact@v4
        with:
          name: repo
          path: |
            ${{ github.workspace }}
            ${{ github.workspace }}/.github

  filter:
    runs-on: ubuntu-latest
    needs: prepare
    outputs:
      n8n: ${{ steps.filter.outputs.n8n }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: repo
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            n8n:
              - 'n8n/**'
              - '!n8n/README.md'
              - '!n8n/docs/**'

  helm-tools:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: repo
      - name: Move repo contents to workspace
        run: |
          mv repo/* .
          mv repo/.[^.]* . || true
      - name: Build helm-tools image if missing
        env:
          IMAGE: ghcr.io/${{ github.repository_owner }}/helm-tools:v2
        run: |
          if ! docker manifest inspect "$IMAGE" >/dev/null 2>&1; then
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker build -t "$IMAGE" -f .github/docker/helm-tools.Dockerfile .
            docker push "$IMAGE"
          else
            echo "$IMAGE already exists"
          fi

  pre-commit:
    runs-on: ubuntu-latest
    needs: [prepare, filter, helm-tools]
    if: needs.filter.outputs.n8n == 'true'
    # Use a tagged image to avoid pulling the floating `latest`
    container:
      image: ghcr.io/${{ github.repository_owner }}/helm-tools:v2
    defaults:
      run:
        working-directory: repo
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: repo
      - name: Set Helm version
        run: echo "HELM_VERSION=$(cat .github/helm-version.txt)" >> "$GITHUB_ENV"
      - name: Setup Helm tools
        uses: ./repo/.github/actions/setup-helm-tools
      - name: Cache pre-commit env
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files $(if [ -n "${{ github.event.pull_request.base.sha }}" ]; then git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }}; else git ls-files; fi)
          cache: true
