name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Setup Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Cache Helm plugins and helm-docs
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.HOME }}/.local/share/helm/plugins
            /usr/local/bin/helm-docs
          key: ${{ runner.os }}-helm-plugins-v1
      - name: Add Helm repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Build chart dependencies
        run: helm dependency build n8n
      - name: Install helm-docs
        run: |
          if [ ! -f /usr/local/bin/helm-docs ]; then
            curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz \
              | tar -xz -C /usr/local/bin helm-docs
          fi
      - name: Install helm-schema-gen plugin
        run: |
          if [ ! -d "$HOME/.local/share/helm/plugins/helm-schema-gen" ]; then
            helm plugin install https://github.com/karuppiah7890/helm-schema-gen.git
          fi
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
