name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    # Use a tagged image to avoid pulling the floating `latest`
    container:
      image: ghcr.io/${{ github.repository_owner }}/helm-tools:v1
    steps:
      - uses: actions/checkout@v4
      - name: Set Helm version
        run: echo "HELM_VERSION=$(cat .github/helm-version.txt)" >> "$GITHUB_ENV"
      - name: Cache helm-unittest plugin
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/.local/share/helm/plugins/helm-unittest
          key: helm-unittest-${{ env.HELM_VERSION }}
          restore-keys: |
            helm-unittest-
      - name: Cache Helm plugins and helm-docs
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.HOME }}/.local/share/helm/plugins
            /usr/local/bin/helm-docs
          key: helm-plugins-${{ env.HELM_VERSION }}
          restore-keys: |
            helm-plugins-
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files $(if [ -n "${{ github.event.pull_request.base.sha }}" ]; then git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }}; else git ls-files; fi)
          cache: true
