---
name: Render Helm Template

'on':
  pull_request:
    paths:
      - 'n8n/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare repo artifact
        run: |
          mkdir repo
          shopt -s dotglob
          rsync -a --exclude=repo "${{ github.workspace }}/" repo/
          rm -rf repo/repo || true
          if [ ! -d repo/.git ]; then
            echo ".git directory missing!"
            exit 1
          fi
          tar -czf repo.tar.gz -C repo .
      - uses: actions/upload-artifact@v4
        with:
          name: repo
          path: repo.tar.gz

  helm-tools:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: repo
          path: .
      - name: Extract repo
        run: |
          mkdir repo
          tar -xzf repo.tar.gz -C repo
          ls -al repo
      - name: Ensure repo context exists
        run: |
          if [ ! -d repo ]; then
            echo "ERROR: repo directory not found!" >&2
            exit 1
          fi
          ls -al repo
      - name: Build helm-tools image if missing
        env:
          IMAGE: ghcr.io/${{ github.repository_owner }}/helm-tools:v4
        run: |
          if ! docker manifest inspect "$IMAGE" >/dev/null 2>&1; then
            echo "${{ secrets.GITHUB_TOKEN }}" | \
              docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker build -t "$IMAGE" \
              -f repo/.github/docker/helm-tools.Dockerfile repo
            docker push "$IMAGE"
          else
            echo "$IMAGE already exists"
          fi

  render:
    runs-on: ubuntu-latest
    container: ghcr.io/anyfavors/helm-tools:v4
    needs: [prepare, helm-tools]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: repo
          path: .
      - name: Extract repo
        run: |
          mkdir repo
          tar -xzf repo.tar.gz -C repo
          ls -al repo
      - name: Set Helm version
        run: |
          echo "HELM_VERSION=$(cat .github/helm-version.txt)" >> "$GITHUB_ENV"
        working-directory: repo
      - name: Cache Helm plugins and helm-docs
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.HOME }}/.local/share/helm/plugins
            /usr/local/bin/helm-docs
          key: helm-plugins-${{ env.HELM_VERSION }}
          restore-keys: |
            helm-plugins-
      - name: Render chart
        id: render
        run: |
          helm template n8n > template.txt
          size=$(wc -c < template.txt)
          echo "size=$size" >> "$GITHUB_OUTPUT"
        working-directory: repo
      - name: Upload template artifact
        if: steps.render.outputs.size > 65000
        uses: actions/upload-artifact@v4
        with:
          name: helm-template
          path: template.txt
      - name: Comment with template
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let body = fs.readFileSync('template.txt', 'utf8');
            const limit = 65000;
            if (body.length > limit) {
              body = body.slice(0, limit) +
                '\n\nOutput truncated. Download artifact for full template.';
            }
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body,
            });
