name: Render Helm Template

on:
  pull_request:
    paths:
      - 'n8n/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  render:
    runs-on: ubuntu-latest
    container: ghcr.io/anyfavors/helm-tools:v1
    steps:
      - uses: actions/checkout@v4
      - name: Set Helm version
        run: echo "HELM_VERSION=$(cat .github/helm-version.txt)" >> "$GITHUB_ENV"
      - name: Cache helm-unittest plugin
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/.local/share/helm/plugins/helm-unittest
          key: helm-unittest-${{ env.HELM_VERSION }}
      - name: Render chart
        id: render
        run: |
          helm template n8n > template.txt
          size=$(wc -c < template.txt)
          echo "size=$size" >> "$GITHUB_OUTPUT"
      - name: Upload template artifact
        if: steps.render.outputs.size > 65000
        uses: actions/upload-artifact@v4
        with:
          name: helm-template
          path: template.txt
      - name: Comment with template
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let body = fs.readFileSync('template.txt', 'utf8');
            const limit = 65000;
            if (body.length > limit) {
              body = body.slice(0, limit) + '\n\nOutput truncated. Download artifact for full template.';
            }
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body,
            });
